config/routes.rb
Rails.application.routes.draw do
  
 root "billboards#index"
 devise_for :users
 
  resources :billboards do 
    resources :artists
  end  

  resources :artists do 
    resources :songs
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard, optional: true
  has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :artists, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :billboards

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  
  def index
    @artists = Artist.all
  end


  def show
    # @songs = @artist.songs.all
  end

  def new
    @artist = Artist.new
    # render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    puts @artist
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
  	if @artist.update(artist_params)
  		redirect_to artists_path
  	else
  		render :edit
  	end
  end

  def destroy
    @artist.destroy
    redirect_to artists_url
  end
  
  private

  # def set_billboard
  #   @billboard = Billboard.find(params[:billboard_id])
  # end  

  def set_artist
  	@artist = Artist.find(params[:id])
  end

  def artist_params
  	params.require(:artist).permit(:name)
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]
  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new 
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save 
      redirect_to billboards_path
    else
      render :new
    end
  end
  
  def update 
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end
  
  def destroy
    # @billboard.songs.update_all(billboard_id: nil)
    @billboard.destroy
    redirect_to billboards_path
  end
      
  private 

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end
    
    def billboard_params
      params.require(:billboard).permit(:name)
    end  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    # before_action :set_billboard
    before_action :set_artist
    before_action :set_song , only: [:show, :edit, :update, :destroy]

    def index
      @songs = @artist.songs
    end
  
  
    def show
    end
  
    def new
      @song = @artist.songs.new
      render partial: "form"
    end
  
    def create
      @song = @artist.songs.new(song_params)
      if @song.save
        redirect_to artist_song_path(@artist, @song)
      else
        render :new
      end
    end
  
    def edit
      render partial: "form"
    end
  
    def update
      if @song.update(song_params)
        redirect_to artist_song_path(@artist, @song)
      else
        render :edit
      end
    end

    def destroy
      @song.destroy
      redirect_to artist_path(@artist)
  end
  
    private
  
    # def set_billboard
    #   @billboard = Billboard.find(params[:billboard_id])
    # end  
  
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
  
    def set_song
      @song = @artist.songs.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :belongs_to, :belongs_to)
    end

  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: 'ui button green' %>
  </div>

<% end %>  

app/views/artists/edit.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>

<br>
<%= render 'form', artist: @artist %>
<br>
<%= link_to 'Back', artists_path, class: "ui button green"%>

app/views/artists/index.html.erb
<br>
<br>
<div class="center-align">
  <div class="hoverable">
    <h1>Click on Artist to view song library</h1>
  </div>
</div>
<br>
<br>
<div class="div-container">
<%= link_to "New Artist", new_artist_path, class: "ui button blue" %>
<%= link_to "Back to Billboards", billboards_path, class: "ui button green" %>
</div>
<br>
<br>
<% @artists.each do |artist| %>
  <div class="center-align">
    <div class="card-panel hoverable">
      <h1><%= link_to artist.name, artist_path(artist) %></h1>
    </div>
  </div>
  <br>
  <br>
  <div class="div-container">
  <%= link_to "Delete this Artist", artist, method: :delete, class: "ui button red" %>
  <%= link_to "Edit this Artist", edit_artist_path(artist), class: "ui button yellow" %>
  </div>

  <% end %>

app/views/artists/new.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>

<br>
<%= render 'form', artist: @artist %>
<br>
<%= link_to 'Back', artists_path, class: "ui button green" %>

app/views/artists/show.html.erb
  <div class="hoverable">
    <div class="center-align">
      <br>
      <br>
      <%= link_to 'View Songs', artist_songs_path(@artist), class: "ui button purple" %> 
      <%= link_to 'Back', artists_path, class: "ui button blue" %>
    </div>
  </div>

app/views/billboards/_form.html.erb
<%= form_for @billboard do |f| %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  
  <div class="result">
    <%= f.submit nil, class: "ui button grey" %>
  </div>
<% end %>  

app/views/billboards/edit.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>

<%= form_with(model: @billboard, local: true, class: "form") do |f| %> 
  <div class="input">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="div-container" >
  <div class="button">
        <%= f.button class: "ui button yellow" %>
        </div>
        <%= link_to "Back to Billboards", billboards_path, class: "ui button orange" %>
</div>
</div>
  <% end %>

app/views/billboards/index.html.erb
<br>
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
  <h1>Welcome, <%= current_user.first_name %></h1>
<br>
<h2>Billboard Music Charts </h2>
<div class="center-align">
  <div class="hoverable">
  </div>
</div>
<br>
    <% @billboards.each do |billboard| %>
      <div class="center-align">
      <div class="card-panel hoverable">
      <h2><%= link_to billboard.name, billboard_path(billboard) %></h2>
      </div>
      </div>
      <br>
      

<% end %>




  

app/views/billboards/new.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>
<%= form_with(model: @billboard, local: true, class: "form") do |f| %> 
  <div class="input">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="div-container" >
  <div class="button">
        <%= f.button class: "ui button orange" %>
        </div>
        <%= link_to "Back to Billboards", billboards_path, class: "ui button red" %>
</div>
</div>
  <% end %>

app/views/billboards/show.html.erb
<div class="center-align">
  <div class="hoverable">
    <h1><%= @billboard.name %></h1>
    <p> What would you like to do?</p>
      <br>
      <div class="div-container">
      <%= link_to "New Billboard", new_billboard_path, class: "ui button blue" %>
      <%= link_to 'All Artists', artists_path, class: 'ui button orange' %>
      <%= link_to "Edit this Billboard", edit_billboard_path(@billboard), class: "ui button yellow" %>
      <%= link_to "Delete this Billboard", billboard_path(@billboard), method: :delete, class: "ui button green", data: { confirm: 'Are you sure?' } %>
      </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicChart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui container">
   <%= render 'layouts/navbar' %>
   
    <%= yield %> 
  </div>  
  <body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: 'ui button' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>
<br>
  <%= render 'form', song: @song %>
<br>
  <%= link_to 'Back', artist_songs_path(@artist), class: "ui button orange"%>

app/views/songs/index.html.erb
<h1>Song Library</h1>
<ul>
  <% @artist.songs.each do |song| %>
  <% end %>
</ul>

<div class="center-align">
  <div class="hoverable">
  </div>
</div>
<div class="div-container">
<%= link_to "New Song", new_artist_song_path(@artist), class: "ui button green" %>
<%= link_to "Back to Artists", artists_path, class: "ui button yellow blue" %>
</div>
<br>
<br>
<% @songs.each do |song| %>
  <div class="center-align">
    <div class="card-panel hoverable">
      <h1><%= link_to song.name, artist_song_path(@artist, song) %></h1>
    </div>
  </div>
  <br>
  <br>
  <div class="div-container">
  <%= link_to "Delete this Song", artist_song_path(@artist, song), method: :delete, class: "ui button red" %>
  <%= link_to "Edit this Song", edit_artist_song_path(@artist, song), class: "ui button purple" %>
  </div>



  <% end %>

app/views/songs/new.html.erb
<div class="center-align">
  <div class="hoverable">
  </div>
</div>
      
<br>
  <%= render 'form', song: @song %>
<br>
  <%= link_to 'Back', artist_songs_path(@artist) %>


  

app/views/songs/show.html.erb
<br/>

<div class="center-align">
  <%= link_to 'Back', artist_songs_path(@artist), class: "ui button orange" %> 
</div>